---
date: "2026-03-06"
title: "Positron Configuration for Research and Data Science"
author: "Riccardo Spada"
format: html
---

## Why I use Positron?

I started learning R using RStudio, which I think is an an excellent IDE. However, when using other languages I started using [VSCode](https://code.visualstudio.com/) and fell in love with how much you can extend and personlize it. However, I didn't like how R was integrated in VSCode. That's when I discovered [Positron](https://positron.app/), a fork of VSCode built by Posit that combines what I like of RStudio with the features of Visual Studio Code.

## Personalizing Positron

Just like VSCode, Positron is highly customizable. Below I share the extensions and settings I use. This are only suggestions and a work in progress, I will keep updating it as I discover new useful stuff. 

### Extensions

- [Air](https://marketplace.visualstudio.com/items?itemName=Posit.air-vscode) for R language support and formatting
- [Shiny](https://marketplace.visualstudio.com/items?itemName=Posit.shiny-vscode) for Shiny app development
- [Quarto](https://marketplace.visualstudio.com/items?itemName=Posit.quarto-vscode) for Quarto documents
- [Rainbow CSV](https://marketplace.visualstudio.com/items?itemName=mechatroner.rainbow-csv) for CSV file editing


### Settings

The settings below are defined in `settings.json`. In Positron you can access this file by opening the command palette (Ctrl + Shift + P) and searching for "Preferences: Open Settings (JSON)". You can copy-paste the settings below in your own file.

<details>
<summary>Click here to expand</summary>
```json
{
    "files.associations": {
        "renv.lock": "json"
    },

    // R specific settings
    "[r]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "Posit.air-vscode"
    },

    // Quarto specific settings
    "[quarto]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "quarto.quarto"
    },

    // Enable Positron's built-in AI assistant
    "positron.assistant.enable": true,

    // Use Material icons in the file explorer
    "workbench.iconTheme": "material-icon-theme",

    // Don't open a welcome tab on launch
    "workbench.startupEditor": "none",

    // Automatically fetch from remote repositories
   "git.autofetch": true,

    // Use RStudio-style keybindings as the baseline
    "workbench.keybindings.rstudioKeybindings": true,

    // Use Git Bash as the default terminal
    "terminal.integrated.defaultProfile.windows": "Git Bash",

    // Ignore trailing whitespace in diffs
    "diffEditor.ignoreTrimWhitespace": true,

    // Custom template for the (custom template) the title bar
    "window.title": "${activeEditorShort}${separator}${rootName}${separator}${profileName}${separator}${activeRepositoryBranchName}",

    // Preview SVGs as rendered images
    "svg.preview.mode": "svg",

    // Collapse summary statistics panel by default
    "dataExplorer.summaryCollapsed": true,

    // Show a vertical ruler at 80 characters
    "editor.rulers": [80],

    // Theme
    "workbench.colorTheme": "Catppuccin Frappé",

    // Disable shell integration to have bash terminal run faster
    "terminal.integrated.shellIntegration.enabled": false

}
```
</details>

### Custom Keyboard Shortcuts

In the settings we enabled the **RStudio keybindings** (`workbench.keybindings.rstudioKeybindings: true`). Additional custom keybindings are defined in `keybindings.json`. You can access this file by again opening the command palette (Ctrl + Shift + P) and searching for "Preferences: Open Keyboard Shortcuts (JSON)". Below are some of the custom keybindings I use, but you can customize them as you like.

`Ctrl + Alt + B`  Toggle the secondary sidebar (auxiliary bar) on/off


<details>
<summary>Click here to expand</summary>
```json
[
{ "key": "ctrl+alt+b",
    "command": "workbench.action.toggleAuxiliaryBar" },
]
```
</details>


